name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: |
        composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
        composer require laravel/breeze --dev

    - name: Install Breeze
      run: |
        php artisan breeze:install blade

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/Desktop/Web_Music_Library
          git pull origin main
          composer install
          composer require laravel/breeze --dev
          php artisan breeze:install blade
          php artisan cache:clear
          php artisan config:cache
